#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
try {
    $app = new Symfony\Component\Console\Application( 'Ensphere Installer', '1.1.0' );
    $app->add( new Ensphere\Installer\NewCommand );
    $app->add( new Ensphere\Installer\NewFrontModuleCommand );
    $app->add( new Ensphere\Installer\NewAdminModuleCommand );
    $app->run();
} catch( Exception $e ) {
    echo $e->getMessage();
}
